# -*- coding: utf-8 -*-

import product_template
import res_partner_family
import res_partner
import insurance_branch
import insurance_fraction
import insurance_product
import insurance_type_risk
import insurance_type_risk_description
import insurance_type_risk_clause
import account_analytic_account
import analytic_history_stage
import analytic_history
import analytic_history_risk_line
import risk_warranty_line
import risk_description_line
import account_invoice
import register_tax_reference
